
addons:
  postgresql: "9.3"

before_script:
  - mysql -e 'create database attr_searchable;'
  - psql -c 'create database attr_searchable;' -U postgres

rvm:
  - 1.9.3
  - rbx
  - 2.0.0
  - 2.1.1
  - jruby-19mode
env:
  - DATABASE=sqlite
  - DATABASE=mysql
  - DATABASE=postgres

install:
  - "travis_retry bundle install"

script: "bundle exec rake test"

